export const refs = {
  btnClose: document.querySelector('.close-btn'),
  btnOpenMenu: document.querySelector('.btn-open-menu'),
  modalOverlay: document.querySelector('.modal-overlay'),
  modal: document.querySelector('.modal-header'),
  close1: document.querySelector('.close1'),
  close2: document.querySelector('.close2'),
  close3: document.querySelector('.close3'),
  close4: document.querySelector('.close4'),
  close5: document.querySelector('.close5'),
  menuTablet: document.querySelector('.menu'),
  listMenu: document.querySelector('.list-menu'),
  skillsList: document.querySelector('.skills-list'),
  aboutMeList: document.querySelector('.about-me-list'),
  skillsSwiper: document.querySelector('.skills-swiper'),
  marqueeLine: document.querySelectorAll('.marquee__line'),
  coversSection: document.querySelector('.covers-section'),
  faqList: document.querySelector('.faq-list'),
};
