export const refs = {
  closeBtnModal: document.querySelector('.close-btn-modal'),
  headerOpenMenuBtn: document.querySelector('.header-open-menu-btn'),
  modalOverlay: document.querySelector('.modal-overlay'),
  close1: document.querySelector('.close1'),
  close2: document.querySelector('.close2'),
  close3: document.querySelector('.close3'),
  close4: document.querySelector('.close4'),
  close5: document.querySelector('.close5'),
  headerMenuBtn: document.querySelector('.header-menu-btn'),
  skillsList: document.querySelector('.skills-list'),
  aboutMeList: document.querySelector('.about-me-list'),
  skillsSwiper: document.querySelector('.skills-swiper'),
  marqueeLine: document.querySelectorAll('.marquee__line'),
  coversSection: document.querySelector('.covers-section'),
  faqList: document.querySelector('.faq-list'),
  dropdownMenuList: document.querySelector('.dropdown-menu-list'),
};
